### PR TITLE
Dynamic scaling of the bar height

### PR DESCRIPTION
**Pull request by sibban81**
Calculated min/max price for today and tomorrow (if exists).
Scaling of the bars is using min/max values of price to dynamic change the height of the bars. If the price is low or not changing much over time it is easeir to see for the user.

### CODE REVIEW

**Comment by sibban81** [comment]
Comparing result of old and new code se below:

Old Code:
image
New Code:
image

**Comment by thegreenmilecornant** [comment]
Looks good 👍 Although for me, the script is now showing an error.

image

**Comment by sibban81** [comment]
A misstake by me. I missed to remove one variable on line 224
`let barHeight = scale(hourPrice * currencyUnitConstant, priceMin, priceMin, 0, height)`
should be:
`let barHeight = scale(hourPrice, priceMin, priceMin, 0, height)`

I fix this later today

**Comment by nicmar** [comment]
Actually i don't prefer this view, when it's on the lock screen, you don't see the colors, so it's impossible to know if the price is high or low. In the "maxPrice" way, where the max is 3.50 or whatever you set, you can always learn that when the bars are small, it's cheap.

Sorry to be "krånglig" but can you add this as "autoScaleHeight = 1;" option in the top and if it's 0, then use the maxPrice instead? :)

**Comment by thegreenmilecornant** [comment]
A feature request and possible solution would be to show min/max values in the widget.

**Comment by sibban81** [comment]
> Actually i don't prefer this view, when it's on the lock screen, you don't see the colors, so it's impossible to know if the price is high or low. In the "maxPrice" way, where the max is 3.50 or whatever you set, you can always learn that when the bars are small, it's cheap.
> 
> Sorry to be "krånglig" but can you add this as "autoScaleHeight = 1;" option in the top and if it's 0, then use the maxPrice instead? :)

Now I understand your height-of-the bar logic :) In north Sweden we don't have the same prices. Here it is expensive if it is 1 kr. I added a parameter autoScaleHeight=true or false. If the user want to use it. Default value is false.

**Comment by sibban81** [comment]
> A feature request and possible solution would be to show min/max values in the widget.

A made a clone of this repo where I added that and some other stuff that I was interested in. Maybe I can add them in an separate pull request. Don't want to clutter all my changes in this repo :)

Heres a taste how it looks:
image

**Comment by nicmar** [comment]
@sibban81 Nice with the bigger text (or is it an illusion?) as well as min/max. Maybe you could use an icon up/down instead of min/max which would also align it. If so, they are arrow.up and arrow.down
Next week i'm getting my solar panels into Tibber, so i'll be adding the produced effect as well, so the lighting symbol has to go :)

**Pull request merged**
