### PR TITLE
Update tibber-graph.js

### PR DESCRIPTION
**Pull request by TobiasLind**
Modified to show tomorrow's electricity prices 0-12 when time is more than 14. Also change color and dims tomorrow's bars even further to indicate that it is tomorrows prices.

### CODE REVIEW

**Comment by TobiasLind** [comment]
Hej.

Grymt intiativ.
Jag gjorde förändringen som du noterade att du vill ha (som även jag ville ha). 
"I'd like to have it change at 13.00 and update the graph to show today 12-23 and tomorrow 00-11. The tomorrow data is already in priceObject.tomorrow"

**Comment by nicmar** [comment]
Aha! Thanks a lot for the PR and update. However it took a little while for me to understand that it was changed. :) Now I see that the first part of the graph shows tomorrow, but I find it a little unintuitive.

The image below shows like how I wanted to show it, so tomorrow comes after today, which i think would be easier to follow.

Are you able to rearrange it to be shown like this? This unfortunately requires you to mess with the numbers and alignments below.. :)

image

**Comment by TobiasLind** [comment]
I tried to do it first but did not get it to work directly so I just wanted to get something out. :)
I agree that it is better to change so that the time scale is 12-12 when tomorrow's prices has arrived.
I will take a look at it next weekend.

/T
________________________________

**Comment by TobiasLind** [comment]
Updated so that timeline changes when new prices arrives.
Skärmavbild 2022-11-01 kl  14 11 57

Skärmavbild 2022-11-01 kl  15 00 58

**Comment by nicmar** [comment]
Nice work!

**Comment by TobiasLind** [comment]
Thanks.
I have some js code in another repo https://github.com/TobiasLind/tibber-dashboard that plot your historical consumption and historical prices of you want to steal any js for other tibber projects.

/T

________________________________

**Pull request merged**
